export const VALIDATION_NUMBERS = {
  MIN_NAME_LENGTH: 3,
  MAX_NAME_LENGTH: 100,
  MIN_PASSWORD_LENGTH: 8,
  MIN_CATEGORY_NAME_LENGTH: 3,
  MAX_CATEGORY_NAME_LENGTH: 100,
  MIN_CONTENT_LENGTH: 10,
} as const;
